[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-example-gateway-cluster"
version = "0.1.0"

[dependencies]
twilight-gateway = { path = "../../gateway" }
futures = "0.3"
tracing-subscriber = "0.2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
