[workspace]
members = [
    "cache/in-memory",
    "command-parser",
    "embed-builder",
    "examples/*",
    "gateway",
    "gateway-queue",
    "http",
    "lavalink",
    "mention",
    "model",
    "standby",
    "twilight",
    "util",
]
