[package]
authors = ["Twilight Contributors"]
categories = ["asynchronous"]
description = "Utility to filter wait for filtered incoming events for the Twilight ecosystem."
documentation = "https://docs.rs/twilight-standby"
edition = "2018"
homepage = "https://twilight.rs/chapter_1_crates/section_6_standby.html"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-standby"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.6.0"

[dependencies]
dashmap = "4.0"
futures-util = { default-features = false, features = ["std"], version = "0.3" }
tokio = { features = ["sync"], version = "1.0" }
twilight-model = { path = "../model" }

# Optional dependencies.
tracing = { optional = true, version = "0.1" }

[dev-dependencies]
static_assertions = "1"
tokio = { features = ["macros", "rt-multi-thread"], version = "1.0" }
twilight-gateway = { path = "../gateway" }

[features]
default = ["tracing"]
