[package]
name = "twilight-example-model-webhook-slash"
version = "0.1.0"
authors = ["Twilight Contributors"]
edition = "2018"

[dependencies]
ed25519-dalek = "1"
hex = "0.4"
hyper = { version = "0.14", features = ["server", "http1", "runtime"] }
once_cell = "1.4.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2"
twilight-model = { path = "../../model" }
