[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-example-gateway-metrics"
version = "0.1.0"

[dependencies]
futures = "0.3"
log = { default-features = false, version = "0.4" }
metrics-runtime = { default-features = false, features = ["metrics-exporter-log", "metrics-observer-json"], version = "0.13" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
tracing-log = { default-features = false, features = ["log-tracer", "std"], version = "0.1" }
tracing-subscriber = { default-features = false, features = ["fmt"], version = "0.2" }
twilight-gateway = { path = "../../gateway", features = ["metrics"] }
