name: Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-cache-inmemory
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-gateway
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-gateway-queue
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-http
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-http-ratelimiting
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-lavalink
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-mention
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-model
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-standby
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-util
          token: ${{ github.token }}

      - uses: ./.github/workflows/changelog-job.yml
        with:
          name: twilight-validate
          token: ${{ github.token }}
