name: Deploy documentation

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "twilight*/**"
      - "Cargo.toml"

jobs:
  deploy-docs:
    name: Deploy docs to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Add problem matchers
        run: echo "::add-matcher::.github/rust.json"

      - name: Build docs
        env:
          RUSTDOCFLAGS: --cfg docsrs
          RUSTFLAGS: -C target-cpu=haswell
        run: cargo doc --no-deps --all-features --workspace --exclude book

      - name: Prepare docs
        run: |
          echo '<meta http-equiv="refresh" content="0;url=twilight/index.html">' > target/doc/index.html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_BOT }}
          publish_branch: gh-pages
          publish_dir: target/doc
          allow_empty_commit: true
          cname: api.twilight.rs
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
