name: Check documentation

on: 
  push:
    branches:
      - main
  pull_request:
    

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Build docs
        env:
          RUSTDOCFLAGS: --cfg docsrs -D broken_intra_doc_links
        run: |
          cargo doc --workspace --no-deps --features=permission-calculator
          cargo doc -p twilight-util --no-deps --all-features
      
      - name: Remove examples
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: $(grep -h '^name' **/examples/**/Cargo.toml | cut -d'"' -f2 | sed 's/-/_/g' | xargs -I '{}' rm -rf ./target/doc/{})

      - name: Prepare docs
        run: |
          echo '<meta http-equiv="refresh" content="0;url=twilight/index.html">' > target/doc/index.html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: target/doc
          allow_empty_commit: true
          cname: api.twilight.rs


  sync-readme:
    name: Sync readme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install cargo-sync-readme
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-sync-readme

      - name: Run in command-parser
        run: cd command-parser && cargo sync-readme --check
      - name: Run in gateway
        run: cd gateway && cargo sync-readme --check
      - name: Run in http
        run: cd http && cargo sync-readme --check
      - name: Run in lavalink
        run: cd lavalink && cargo sync-readme --check
      - name: Run in model
        run: cd model && cargo sync-readme --check
      - name: Run in standby
        run: cd standby && cargo sync-readme --check
      - name: Run in twilight
        run: cd twilight && cargo sync-readme --check
      - name: Run in embed-builder
        run: cd embed-builder && cargo sync-readme --check
      - name: Run in mention
        run: cd mention && cargo sync-readme --check
      - name: Run in util
        run: cd util && cargo sync-readme --check
