name: Lint

# Only run push on pushes to main, to prevent actions from running twice on PRs
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        env:
          # Use `haswell` instead of `native` due to some GitHub Actions
          # runners not supporting some `avx512` instructions.
          RUSTFLAGS: "-C target-cpu=haswell"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --benches --examples --tests --all-features

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  codespell:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run Codespell
        uses: codespell-project/actions-codespell@master
