name: Deploy documentation

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-docs:
    name: Deploy docs to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Build docs
        env:
          RUSTDOCFLAGS: --cfg docsrs -D broken_intra_doc_links
        run: |
          exclude_examples=($(grep -h '^name' examples/**/Cargo.toml | cut -d'"' -f2 | xargs -I '{}' echo '--exclude {}'))
          cargo doc --workspace --no-deps --features=permission-calculator "${exclude_examples[@]}"
          cargo doc -p twilight-util --no-deps --all-features

      - name: Prepare docs
        run: |
          echo '<meta http-equiv="refresh" content="0;url=twilight/index.html">' > target/doc/index.html

      - name: Deploy docs
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: target/doc
          allow_empty_commit: true
          cname: api.twilight.rs
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

      - name: Deploy dev docs
        if: ${{ github.event_name == 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: target/doc
          allow_empty_commit: true
          cname: api.twilight.rs
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          # PR-specific configuration option
          destination_dir: pull/${{ github.event.pull_request.number }}

      - name: Comment link to dev docs deployment
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@latest
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The documentation has been [built and deployed] to this repository's
            `gh-pages` branch while this pull request remains open. 

            [built and deployed]: https://api.twilight.rs/pull/${{ github.event.pull_request.number }}/twilight/index.html
