name: Undeploy dev documentation 

on:
  pull_request:
    types: [closed]

jobs:
  undeploy-dev-docs:
    name: Remove dev docs 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      
      - name: Remove pull request subdirectory
        run: |
          /usr/bin/git remote rm origin
          /usr/bin/git remote add origin git@github.com:twilight-rs/twilight.git
          /usr/bin/git config user.name github-actions[bot]
          /usr/bin/git config user.email github-action[bot]@users.noreply.github.com
          /usr/bin/git rm -r pull/${{ github.event.pull_request.number }}
          /usr/bin/git commit --allow-empty -m "deploy pr: ${{ github.event.pull_request.number }} (${{ github.event.pull_request.GITHUB_SHA }})"
          /usr/bin/git push origin gh-pages